### ISSUE TITLE
webgui creation error

### ISSUE THREAD

**Issue by robotfishe** [ph1p/ikea-led-obegraensad#26]
I've been working on adding a weather mode to your code, and I have it working but I can only access it by sending a websocket command because it's not in the dropdown list in the GUI. When I try to recreate the webgui using the steps in the readme, I get soome errors in response to the command "npm run dev":

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.0.0 dev script.

Any ideas what's happening here?

**Comment by robotfishe** [comment]
Figured it out - whitespace in my Windows user folder name was causing npm to error out somewhere.
